security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_MANAGER:    [ROLE_USER, ROLE_COMPANY, ROLE_STRUCTURE]
        ROLE_ADMIN:       ROLE_MANAGER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        main:
            logout_on_user_change: true
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                success_handler: authentication.handler.login_success_handler

            logout:       true
            anonymous:    true
            access_denied_url: /redirect


    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, role: ROLE_SUPER_ADMIN }
        - { path: ^/manager, role: ROLE_MANAGER }
        - { path: ^/inscription, role: ROLE_USER }
        - { path: ^/organization/new, role: ROLE_USER }
        - { path: ^/waiting, role: ROLE_USER }
        - { path: ^/organization, role: [ROLE_COMPANY, ROLE_STRUCTURE] }
        - { path: ^/activity/[0-9]+$, role: [ROLE_COMPANY, ROLE_STRUCTURE] }
        - { path: ^/activity, role: ROLE_STRUCTURE }
        - { path: ^/offer/[0-9]+/relation, role: ROLE_COMPANY }
        - { path: ^/offer, role: ROLE_STRUCTURE }
        - { path: ^/contract, role: [ROLE_COMPANY, ROLE_STRUCTURE] }
